/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as StatusRouteImport } from './routes/status'
import { Route as KeranjangRouteImport } from './routes/keranjang'
import { Route as KategoriRouteImport } from './routes/kategori'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AkunRouteImport } from './routes/akun'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdukSlugRouteImport } from './routes/produk.$slug'
import { Route as PembayaranQrisRouteImport } from './routes/pembayaran.qris'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const KeranjangRoute = KeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriRoute = KategoriRouteImport.update({
  id: '/kategori',
  path: '/kategori',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunRoute = AkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukSlugRoute = ProdukSlugRouteImport.update({
  id: '/produk/$slug',
  path: '/produk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PembayaranQrisRoute = PembayaranQrisRouteImport.update({
  id: '/pembayaran/qris',
  path: '/pembayaran/qris',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/akun': typeof AkunRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/kategori': typeof KategoriRoute
  '/keranjang': typeof KeranjangRoute
  '/status': typeof StatusRoute
  '/wishlist': typeof WishlistRoute
  '/pembayaran/qris': typeof PembayaranQrisRoute
  '/produk/$slug': typeof ProdukSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/akun': typeof AkunRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/kategori': typeof KategoriRoute
  '/keranjang': typeof KeranjangRoute
  '/status': typeof StatusRoute
  '/wishlist': typeof WishlistRoute
  '/pembayaran/qris': typeof PembayaranQrisRoute
  '/produk/$slug': typeof ProdukSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/akun': typeof AkunRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/kategori': typeof KategoriRoute
  '/keranjang': typeof KeranjangRoute
  '/status': typeof StatusRoute
  '/wishlist': typeof WishlistRoute
  '/pembayaran/qris': typeof PembayaranQrisRoute
  '/produk/$slug': typeof ProdukSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/akun'
    | '/auth'
    | '/checkout'
    | '/kategori'
    | '/keranjang'
    | '/status'
    | '/wishlist'
    | '/pembayaran/qris'
    | '/produk/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/akun'
    | '/auth'
    | '/checkout'
    | '/kategori'
    | '/keranjang'
    | '/status'
    | '/wishlist'
    | '/pembayaran/qris'
    | '/produk/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/akun'
    | '/auth'
    | '/checkout'
    | '/kategori'
    | '/keranjang'
    | '/status'
    | '/wishlist'
    | '/pembayaran/qris'
    | '/produk/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AkunRoute: typeof AkunRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  KategoriRoute: typeof KategoriRoute
  KeranjangRoute: typeof KeranjangRoute
  StatusRoute: typeof StatusRoute
  WishlistRoute: typeof WishlistRoute
  PembayaranQrisRoute: typeof PembayaranQrisRoute
  ProdukSlugRoute: typeof ProdukSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keranjang': {
      id: '/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof KeranjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori': {
      id: '/kategori'
      path: '/kategori'
      fullPath: '/kategori'
      preLoaderRoute: typeof KategoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun': {
      id: '/akun'
      path: '/akun'
      fullPath: '/akun'
      preLoaderRoute: typeof AkunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$slug': {
      id: '/produk/$slug'
      path: '/produk/$slug'
      fullPath: '/produk/$slug'
      preLoaderRoute: typeof ProdukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pembayaran/qris': {
      id: '/pembayaran/qris'
      path: '/pembayaran/qris'
      fullPath: '/pembayaran/qris'
      preLoaderRoute: typeof PembayaranQrisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AkunRoute: AkunRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  KategoriRoute: KategoriRoute,
  KeranjangRoute: KeranjangRoute,
  StatusRoute: StatusRoute,
  WishlistRoute: WishlistRoute,
  PembayaranQrisRoute: PembayaranQrisRoute,
  ProdukSlugRoute: ProdukSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
